const electricalLinkBase = "/lessons/elec/electrical/";
const electrokineticLinkBase = "/lessons/elec/electrokinetic/";
const electronicLinkBase = "/lessons/elec/electronic/";
export const electrokinetics = [
  {
    link: electrokineticLinkBase + "arqs",
    title: "Lois dans l'ARQS",
    tagName: "L1",
    tagColor: "is-primary",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "condo",
    title: "Condensateur et bobine, circuits RC et RL",
    tagName: "L1",
    tagColor: "is-primary",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "3",
    title: "Puissance en régime stationnaire",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "4",
    title: "Circuit RLC série",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "5",
    title: "Régime sinusoïdal",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "6",
    title: "Résonnances RLC série",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electrokineticLinkBase + "7",
    title: "Filtrage analogique",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
];

export const electronics = [
  {
    link: electronicLinkBase + "1",
    title: "Modélisation du transistor",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "2",
    title: "Amplificateur opérationnel",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "3",
    title: "Analyse spectrale",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "4",
    title: "Échantillonnage",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "5",
    title: "Bande de base",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "6",
    title: "Boucle à verrouillage de phase",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "7",
    title: "Modulation analogique",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "8",
    title: "Modulation numérique",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "9",
    title: "Représentation entiers/flottants",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "10",
    title: "Filtrage numérique",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electronicLinkBase + "11",
    title: "Hyperfréquence",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
];

export const electricals = [
  {
    link: electricalLinkBase + "1",
    title: "Systèmes polyphasés équilibrés",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "2",
    title: "Puissances déformantes/harmoniques",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "3",
    title: "Modélisation du transformateur",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "4",
    title: "Hacheurs",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "5",
    title: "Alimentations à découpage",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "6",
    title: "Redresseurs passifs",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "7",
    title: "Redresseurs commandés",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
  {
    link: electricalLinkBase + "8",
    title: "Systèmes polyphasés déséquilibrés",
    tagName: "WIP...",
    tagColor: "is-danger",
    lastDate: "29/03/2023",
  },
];
